import type { RegistryEntry } from './types.js'

export const shadcnCatalog: RegistryEntry[] = [
  {
    id: 'shadcn/button',
    slug: 'button',
    name: 'Button',
    collection: 'shadcn',
    category: 'Actions',
    description: 'Triggers a single action or submits a form.',
    defaultSize: { width: 120, height: 40 },
    defaultProps: { label: 'Button', disabled: false },
    variants: { size: 'md', variant: 'default' },
    keywords: ['action', 'cta', 'submit', 'click'],
  },
  {
    id: 'shadcn/card',
    slug: 'card',
    name: 'Card',
    collection: 'shadcn',
    category: 'Layout',
    description: 'Groups related content and actions in a bordered surface.',
    defaultSize: { width: 320, height: 200 },
    defaultProps: { title: 'Card title', description: 'Card description' },
    variants: { padding: 'md' },
    keywords: ['container', 'surface', 'panel'],
  },
  {
    id: 'shadcn/input',
    slug: 'input',
    name: 'Input',
    collection: 'shadcn',
    category: 'Forms',
    description: 'Captures a single line of text from the user.',
    defaultSize: { width: 240, height: 40 },
    defaultProps: { placeholder: 'Enter text', disabled: false },
    variants: { size: 'md' },
    keywords: ['text field', 'form', 'field'],
  },
  {
    id: 'shadcn/badge',
    slug: 'badge',
    name: 'Badge',
    collection: 'shadcn',
    category: 'Data Display',
    description: 'Highlights a short status or category label.',
    defaultSize: { width: 64, height: 24 },
    defaultProps: { label: 'Badge' },
    variants: { variant: 'default' },
    keywords: ['tag', 'status', 'label', 'pill'],
  },
  {
    id: 'shadcn/dialog',
    slug: 'dialog',
    name: 'Dialog',
    collection: 'shadcn',
    category: 'Overlays',
    description: 'Interrupts the user with content that requires a response.',
    defaultSize: { width: 480, height: 320 },
    defaultProps: { title: 'Dialog title', description: 'Dialog description' },
    variants: { size: 'md' },
    keywords: ['modal', 'popup', 'overlay'],
  },
  {
    id: 'shadcn/tabs',
    slug: 'tabs',
    name: 'Tabs',
    collection: 'shadcn',
    category: 'Navigation',
    description: 'Switches between related views within the same context.',
    defaultSize: { width: 400, height: 240 },
    defaultProps: { defaultValue: 'tab-1' },
    variants: { orientation: 'horizontal' },
    keywords: ['navigation', 'switcher', 'segmented'],
  },
  {
    id: 'shadcn/table',
    slug: 'table',
    name: 'Table',
    collection: 'shadcn',
    category: 'Data Display',
    description: 'Displays rows and columns of structured data.',
    defaultSize: { width: 640, height: 320 },
    defaultProps: { caption: '' },
    variants: { density: 'default' },
    keywords: ['grid', 'rows', 'data', 'list'],
  },
  {
    id: 'shadcn/avatar',
    slug: 'avatar',
    name: 'Avatar',
    collection: 'shadcn',
    category: 'Data Display',
    description: 'Represents a user or entity with an image or initials.',
    defaultSize: { width: 40, height: 40 },
    defaultProps: { alt: 'User', fallback: 'U' },
    variants: { size: 'md' },
    keywords: ['profile', 'photo', 'user'],
  },
  {
    id: 'shadcn/alert',
    slug: 'alert',
    name: 'Alert',
    collection: 'shadcn',
    category: 'Feedback',
    description: 'Calls attention to important information inline.',
    defaultSize: { width: 400, height: 80 },
    defaultProps: { title: 'Heads up', description: 'Alert message' },
    variants: { variant: 'default' },
    keywords: ['notice', 'warning', 'banner', 'message'],
  },
  {
    id: 'shadcn/select',
    slug: 'select',
    name: 'Select',
    collection: 'shadcn',
    category: 'Forms',
    description: 'Lets the user choose one option from a list.',
    defaultSize: { width: 240, height: 40 },
    defaultProps: { placeholder: 'Select an option', disabled: false },
    variants: { size: 'md' },
    keywords: ['dropdown', 'picker', 'form', 'combobox'],
  },
]

export const layoutCatalog: RegistryEntry[] = [
  {
    id: 'layout/stack',
    slug: 'stack',
    name: 'Stack',
    collection: 'layout',
    category: 'Layout',
    description: 'Arranges children in a single row or column with consistent spacing.',
    defaultSize: { width: 320, height: 200 },
    defaultProps: { gap: 16 },
    variants: { direction: 'vertical' },
    keywords: ['flex', 'vbox', 'hbox', 'flow'],
  },
  {
    id: 'layout/grid',
    slug: 'grid',
    name: 'Grid',
    collection: 'layout',
    category: 'Layout',
    description: 'Arranges children into a fixed number of columns and rows.',
    defaultSize: { width: 480, height: 320 },
    defaultProps: { columns: 3, gap: 16 },
    variants: { flow: 'row' },
    keywords: ['columns', 'rows', 'layout'],
  },
  {
    id: 'layout/container',
    slug: 'container',
    name: 'Container',
    collection: 'layout',
    category: 'Layout',
    description: 'Constrains content width and centers it on the page.',
    defaultSize: { width: 960, height: 480 },
    defaultProps: { maxWidth: 1200 },
    variants: { padding: 'md' },
    keywords: ['wrapper', 'page', 'bounds'],
  },
  {
    id: 'layout/section',
    slug: 'section',
    name: 'Section',
    collection: 'layout',
    category: 'Layout',
    description: 'Groups a distinct region of page content.',
    defaultSize: { width: 960, height: 320 },
    defaultProps: { background: 'transparent' },
    variants: { padding: 'lg' },
    keywords: ['region', 'block', 'landmark'],
  },
  {
    id: 'layout/heading',
    slug: 'heading',
    name: 'Heading',
    collection: 'layout',
    category: 'Typography',
    description: 'Introduces a section with a short title.',
    defaultSize: { width: 320, height: 40 },
    defaultProps: { text: 'Heading' },
    variants: { level: 'h2' },
    keywords: ['title', 'headline', 'text'],
  },
  {
    id: 'layout/text-block',
    slug: 'text-block',
    name: 'Text Block',
    collection: 'layout',
    category: 'Typography',
    description: 'Displays a paragraph of body copy.',
    defaultSize: { width: 320, height: 96 },
    defaultProps: { text: 'Body text' },
    variants: { size: 'md' },
    keywords: ['paragraph', 'copy', 'body'],
  },
]

export const catalog: RegistryEntry[] = [...shadcnCatalog, ...layoutCatalog]
