/* Generated by scripts/build-ui-vocabulary-data.mjs. Do not edit directly. */

export type TermCategory = "input" | "selection" | "action" | "structure" | "feedback" | "data-display"

export type VocabularyTerm = {
  id: string
  status: "draft" | "reviewed" | "published"
  category: TermCategory
  ko: { name: string; aliases: string[] }
  en: { name: string; aliases: string[] }
  one_liner: string
  description: string
  visual_anatomy: string[]
  when_to_use: string[]
  anti_use: string[]
  prompt_phrases: string[]
  asset: { kind: string; variant: string; props?: Record<string, unknown> }
  sources: { source_id: string; note?: string }[]
  confidence: "low" | "medium" | "high"
}

export const terms = [
  {
    "id": "text-field",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "입력창",
      "aliases": [
        "텍스트 필드",
        "인풋",
        "입력 요소"
      ]
    },
    "en": {
      "name": "Text field",
      "aliases": [
        "Input",
        "Text input"
      ]
    },
    "one_liner": "짧은 텍스트를 한 줄로 입력받는 요소.",
    "description": "이름, 제목, 이메일처럼 짧은 문자열을 사용자가 직접 입력할 때 쓴다.",
    "visual_anatomy": [
      "label or placeholder",
      "rectangular input container",
      "text caret",
      "optional helper text"
    ],
    "when_to_use": [
      "짧은 값을 직접 입력받을 때",
      "폼에서 사용자가 값을 수정해야 할 때"
    ],
    "anti_use": [
      "긴 본문에는 textarea를 쓴다",
      "정해진 보기 중 선택이면 select나 radio group을 검토한다"
    ],
    "prompt_phrases": [
      "이름을 입력하는 text field를 넣어줘",
      "검색어 입력창을 상단에 배치해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "text-field",
      "props": {
        "state": "default"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "text field component naming and anatomy"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "search-field",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "검색창",
      "aliases": [
        "검색 입력창",
        "search input",
        "서치바"
      ]
    },
    "en": {
      "name": "Search field",
      "aliases": [
        "Search input",
        "Search bar"
      ]
    },
    "one_liner": "검색어를 입력해 목록이나 콘텐츠를 찾는 입력 요소.",
    "description": "돋보기 아이콘, placeholder, 지우기 버튼이 함께 쓰이는 경우가 많다.",
    "visual_anatomy": [
      "magnifying glass icon",
      "input container",
      "placeholder text",
      "optional clear button"
    ],
    "when_to_use": [
      "리스트나 데이터가 많아 사용자가 빠르게 찾게 할 때",
      "이름이나 키워드로 필터링할 때"
    ],
    "anti_use": [
      "항목 수가 적으면 category filter가 더 단순할 수 있다",
      "복잡한 조건 검색은 filter panel을 쓴다"
    ],
    "prompt_phrases": [
      "카드 목록 위에 검색창을 넣어줘",
      "검색창 안에 돋보기 아이콘을 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "search-field",
      "props": {
        "state": "default"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "search component pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "textarea",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "텍스트영역",
      "aliases": [
        "긴 글 입력창",
        "여러 줄 입력",
        "textarea"
      ]
    },
    "en": {
      "name": "Textarea",
      "aliases": [
        "Multiline text field",
        "Text area"
      ]
    },
    "one_liner": "여러 줄의 긴 텍스트를 입력받는 요소.",
    "description": "메모, 소개글, 문의 내용처럼 길이가 길거나 줄바꿈이 필요한 입력에 쓴다.",
    "visual_anatomy": [
      "label",
      "multiline box",
      "resize corner or fixed height",
      "helper text"
    ],
    "when_to_use": [
      "사용자가 문장이나 본문을 입력할 때",
      "줄바꿈이 의미 있는 내용을 받을 때"
    ],
    "anti_use": [
      "한 줄 값에는 text field가 더 적합하다",
      "rich formatting이 필요하면 editor를 쓴다"
    ],
    "prompt_phrases": [
      "문의 내용을 쓰는 textarea를 넣어줘",
      "긴 설명 입력 영역을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "textarea",
      "props": {
        "rows": 3
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "textarea component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "select",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "선택창",
      "aliases": [
        "셀렉트",
        "드롭다운 선택",
        "select box"
      ]
    },
    "en": {
      "name": "Select",
      "aliases": [
        "Select box",
        "Dropdown select"
      ]
    },
    "one_liner": "정해진 보기 중 하나를 선택하는 입력 요소.",
    "description": "현재 선택값과 펼침 화살표를 보여주고, 클릭하면 옵션 목록을 연다.",
    "visual_anatomy": [
      "selected value",
      "trigger container",
      "chevron icon",
      "option list"
    ],
    "when_to_use": [
      "선택지가 정해져 있고 하나만 고를 때",
      "공간을 아껴야 할 때"
    ],
    "anti_use": [
      "선택지가 2-4개면 radio group이나 segmented control이 더 잘 보인다",
      "검색이 필요하면 combobox를 쓴다"
    ],
    "prompt_phrases": [
      "카테고리를 고르는 select를 넣어줘",
      "옵션 목록에서 하나 고르는 드롭다운을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "select",
      "props": {
        "open": false
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "menus and select-like input behavior"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "combobox",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "콤보박스",
      "aliases": [
        "검색 가능한 선택창",
        "자동완성 선택",
        "combobox"
      ]
    },
    "en": {
      "name": "Combobox",
      "aliases": [
        "Autocomplete select",
        "Searchable select"
      ]
    },
    "one_liner": "입력과 선택을 함께 제공하는 검색 가능한 선택 요소.",
    "description": "사용자가 텍스트를 입력해 옵션을 필터링하고 목록에서 값을 고를 수 있다.",
    "visual_anatomy": [
      "input trigger",
      "typed query",
      "filtered option list",
      "highlighted option"
    ],
    "when_to_use": [
      "선택지가 많아 검색이 필요할 때",
      "사용자가 값을 입력하며 고르게 할 때"
    ],
    "anti_use": [
      "선택지가 적으면 select나 radio group이 더 단순하다",
      "자유 입력만 필요하면 text field를 쓴다"
    ],
    "prompt_phrases": [
      "국가를 검색해서 고르는 combobox를 넣어줘",
      "옵션이 많은 선택창은 검색 가능하게 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "combobox",
      "props": {
        "open": true
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "combobox interaction pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "checkbox",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "체크박스",
      "aliases": [
        "checkbox",
        "다중 선택 체크"
      ]
    },
    "en": {
      "name": "Checkbox",
      "aliases": [
        "Check box"
      ]
    },
    "one_liner": "여러 항목을 각각 켜거나 선택할 수 있는 작은 체크 요소.",
    "description": "동의, 옵션 선택, 다중 선택 리스트에서 쓰이며 체크 표시로 상태를 보여준다.",
    "visual_anatomy": [
      "square control",
      "check mark",
      "label",
      "optional indeterminate state"
    ],
    "when_to_use": [
      "여러 옵션을 동시에 선택할 수 있을 때",
      "약관 동의처럼 yes/no 상태가 필요할 때"
    ],
    "anti_use": [
      "상호 배타적 선택에는 radio group을 쓴다",
      "즉시 켜고 끄는 설정에는 switch가 더 자연스럽다"
    ],
    "prompt_phrases": [
      "약관 동의 체크박스를 넣어줘",
      "여러 개 선택 가능한 checkbox 목록을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "checkbox",
      "props": {
        "checked": true
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "checkbox pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "radio-group",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "라디오그룹",
      "aliases": [
        "라디오 버튼",
        "하나만 선택",
        "radio"
      ]
    },
    "en": {
      "name": "Radio group",
      "aliases": [
        "Radio buttons"
      ]
    },
    "one_liner": "여러 선택지 중 정확히 하나를 고르는 요소 묶음.",
    "description": "각 옵션 앞에 원형 버튼이 있고, 하나를 선택하면 다른 선택은 해제된다.",
    "visual_anatomy": [
      "group label",
      "circular controls",
      "selected dot",
      "option labels"
    ],
    "when_to_use": [
      "선택지가 적고 모두 보여줘야 할 때",
      "사용자가 하나만 선택해야 할 때"
    ],
    "anti_use": [
      "여러 개 선택 가능하면 checkbox를 쓴다",
      "선택지가 많으면 select를 검토한다"
    ],
    "prompt_phrases": [
      "요금제를 하나 고르는 radio group을 넣어줘",
      "결제 방식을 라디오 버튼으로 선택하게 해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "radio-group",
      "props": {
        "selected": 1
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "radio group pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "switch",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "스위치",
      "aliases": [
        "토글",
        "toggle",
        "켜기 끄기"
      ]
    },
    "en": {
      "name": "Switch",
      "aliases": [
        "Toggle switch",
        "Toggle"
      ]
    },
    "one_liner": "설정을 즉시 켜거나 끄는 요소.",
    "description": "손잡이가 좌우로 움직이며 on/off 상태를 직관적으로 보여준다.",
    "visual_anatomy": [
      "track",
      "thumb",
      "on/off position",
      "label"
    ],
    "when_to_use": [
      "설정을 바로 활성화하거나 비활성화할 때",
      "변경 결과가 즉시 적용될 때"
    ],
    "anti_use": [
      "폼 제출 전까지 확정되지 않는 값에는 checkbox가 더 명확할 수 있다",
      "여러 선택지 중 하나는 radio group을 쓴다"
    ],
    "prompt_phrases": [
      "알림을 켜고 끄는 toggle switch를 넣어줘",
      "다크모드 스위치를 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "switch",
      "props": {
        "checked": true
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "switch component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "slider",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "슬라이더",
      "aliases": [
        "range slider",
        "값 조절 바"
      ]
    },
    "en": {
      "name": "Slider",
      "aliases": [
        "Range slider"
      ]
    },
    "one_liner": "연속적인 값이나 범위를 손잡이로 조절하는 요소.",
    "description": "트랙 위 thumb를 움직여 볼륨, 가격, 강도 같은 값을 조정한다.",
    "visual_anatomy": [
      "track",
      "filled range",
      "thumb",
      "value label"
    ],
    "when_to_use": [
      "정확한 숫자보다 대략적인 조절이 중요할 때",
      "값의 크기를 시각적으로 보여주고 싶을 때"
    ],
    "anti_use": [
      "정확한 숫자 입력이 필요하면 number input을 쓴다",
      "선택지가 이산적이면 segmented control이나 radio를 쓴다"
    ],
    "prompt_phrases": [
      "볼륨을 조절하는 slider를 넣어줘",
      "가격 범위를 고르는 range slider를 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "slider",
      "props": {
        "value": 65
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "slider component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "date-picker",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "날짜 선택",
      "aliases": [
        "데이트피커",
        "달력 입력",
        "date picker"
      ]
    },
    "en": {
      "name": "Date picker",
      "aliases": [
        "Calendar picker"
      ]
    },
    "one_liner": "달력 UI로 날짜를 선택하는 입력 요소.",
    "description": "날짜 입력창과 달력 팝오버를 함께 제공해 날짜를 직접 고르게 한다.",
    "visual_anatomy": [
      "date input",
      "calendar icon",
      "calendar popover",
      "selected day"
    ],
    "when_to_use": [
      "예약일이나 마감일처럼 날짜를 고르게 할 때",
      "날짜 형식 오류를 줄이고 싶을 때"
    ],
    "anti_use": [
      "연도나 월만 고르면 simpler select가 낫다",
      "자유 텍스트 날짜는 오류가 많다"
    ],
    "prompt_phrases": [
      "예약 날짜를 고르는 date picker를 넣어줘",
      "달력으로 마감일을 선택하게 해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "date-picker",
      "props": {
        "date": "2026-05-20"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "date picker component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "file-upload",
    "status": "draft",
    "category": "input",
    "ko": {
      "name": "파일 업로드",
      "aliases": [
        "파일 선택",
        "첨부",
        "upload input"
      ]
    },
    "en": {
      "name": "File upload",
      "aliases": [
        "File input",
        "Upload button"
      ]
    },
    "one_liner": "사용자가 로컬 파일을 선택하거나 끌어다 놓게 하는 입력 요소.",
    "description": "파일 선택 버튼, 드롭존, 선택된 파일 이름을 함께 보여주는 경우가 많다.",
    "visual_anatomy": [
      "upload icon",
      "file button or dropzone",
      "filename",
      "optional progress"
    ],
    "when_to_use": [
      "이미지나 문서를 첨부받을 때",
      "파일 업로드 상태를 보여줘야 할 때"
    ],
    "anti_use": [
      "단순 링크 입력에는 text field를 쓴다",
      "대용량 업로드는 별도 progress와 error recovery가 필요하다"
    ],
    "prompt_phrases": [
      "프로필 이미지를 올리는 file upload를 넣어줘",
      "파일 선택 버튼과 업로드 상태를 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "file-upload",
      "props": {
        "state": "idle"
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "input and form composition"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "tabs",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "탭",
      "aliases": [
        "탭 메뉴",
        "tab"
      ]
    },
    "en": {
      "name": "Tabs",
      "aliases": [
        "Tab list"
      ]
    },
    "one_liner": "같은 영역 안에서 관련 화면이나 패널을 전환하는 요소.",
    "description": "탭 목록과 선택된 탭 패널로 구성되며 현재 위치를 강조한다.",
    "visual_anatomy": [
      "tab list",
      "active tab",
      "inactive tabs",
      "tab panel"
    ],
    "when_to_use": [
      "같은 맥락의 콘텐츠를 몇 개 섹션으로 나눌 때",
      "화면 이동 없이 내용을 전환할 때"
    ],
    "anti_use": [
      "서로 관련 없는 페이지 이동에는 navigation을 쓴다",
      "탭이 너무 많으면 overflow나 다른 구조를 검토한다"
    ],
    "prompt_phrases": [
      "상세 화면에 탭 메뉴를 넣어줘",
      "개요와 설정을 tabs로 전환하게 해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "tabs",
      "props": {
        "active": 0
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "tabs pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "segmented-control",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "세그먼트 버튼",
      "aliases": [
        "분할 버튼",
        "segmented control",
        "옵션 토글"
      ]
    },
    "en": {
      "name": "Segmented control",
      "aliases": [
        "Segmented button"
      ]
    },
    "one_liner": "몇 개의 선택지를 버튼처럼 나란히 보여주고 하나를 선택하는 요소.",
    "description": "필터 모드나 보기 방식을 빠르게 전환할 때 쓰며 선택된 segment를 강조한다.",
    "visual_anatomy": [
      "group container",
      "segments",
      "active segment",
      "labels"
    ],
    "when_to_use": [
      "2-5개 정도의 선택지를 항상 보여주고 싶을 때",
      "보기 모드나 필터를 빠르게 바꿀 때"
    ],
    "anti_use": [
      "선택지가 많으면 select를 쓴다",
      "다중 선택이면 checkbox나 chips를 검토한다"
    ],
    "prompt_phrases": [
      "일간 주간 월간을 고르는 segmented control을 넣어줘",
      "보기 방식을 세그먼트 버튼으로 전환하게 해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "segmented-control",
      "props": {
        "active": 1
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "segmented buttons"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "dropdown-menu",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "드롭다운 메뉴",
      "aliases": [
        "더보기 메뉴",
        "펼침 메뉴",
        "dropdown"
      ]
    },
    "en": {
      "name": "Dropdown menu",
      "aliases": [
        "Menu",
        "Popup menu"
      ]
    },
    "one_liner": "버튼을 누르면 아래로 펼쳐지는 명령 또는 선택 목록.",
    "description": "숨겨진 동작이나 옵션을 한 곳에 모아 표시한다.",
    "visual_anatomy": [
      "trigger button",
      "chevron or more icon",
      "floating menu",
      "menu items"
    ],
    "when_to_use": [
      "자주 쓰지 않는 명령을 숨길 때",
      "공간을 아끼며 옵션을 제공할 때"
    ],
    "anti_use": [
      "중요한 주요 행동은 숨기지 않는다",
      "값 선택이 목적이면 select나 combobox를 검토한다"
    ],
    "prompt_phrases": [
      "카드 오른쪽에 더보기 dropdown menu를 넣어줘",
      "정렬 옵션을 드롭다운 메뉴로 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "dropdown-menu",
      "props": {
        "open": true
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "menu button pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "command-palette",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "커맨드 팔레트",
      "aliases": [
        "명령 검색창",
        "command menu",
        "빠른 실행"
      ]
    },
    "en": {
      "name": "Command palette",
      "aliases": [
        "Command menu"
      ]
    },
    "one_liner": "검색으로 화면 이동이나 명령 실행을 빠르게 찾는 오버레이.",
    "description": "입력창과 결과 목록을 함께 보여주며 키보드 중심 탐색에 적합하다.",
    "visual_anatomy": [
      "overlay panel",
      "command input",
      "grouped results",
      "keyboard hint"
    ],
    "when_to_use": [
      "기능이 많고 빠른 검색 실행이 필요할 때",
      "파워 유저용 단축 흐름이 필요할 때"
    ],
    "anti_use": [
      "초보자에게 필수 기능을 숨기는 용도로 쓰지 않는다",
      "항목이 적으면 일반 검색이나 메뉴가 더 쉽다"
    ],
    "prompt_phrases": [
      "Ctrl K로 여는 command palette를 넣어줘",
      "명령어를 검색해서 실행하는 팔레트를 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "command-palette",
      "props": {
        "open": true
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "command component"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "breadcrumb",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "브레드크럼",
      "aliases": [
        "현재 위치 경로",
        "breadcrumb"
      ]
    },
    "en": {
      "name": "Breadcrumb",
      "aliases": [
        "Breadcrumb navigation"
      ]
    },
    "one_liner": "현재 페이지가 전체 구조에서 어디인지 보여주는 경로 표시.",
    "description": "홈부터 현재 페이지까지 상위 경로를 링크로 나열한다.",
    "visual_anatomy": [
      "ancestor links",
      "separators",
      "current page label"
    ],
    "when_to_use": [
      "계층 구조가 깊은 사이트에서 현재 위치를 알려줄 때",
      "상위 페이지로 돌아가기 쉽게 할 때"
    ],
    "anti_use": [
      "단일 페이지나 얕은 구조에는 불필요하다",
      "주요 navigation을 대체하지 않는다"
    ],
    "prompt_phrases": [
      "상단에 홈 > 대시보드 > 설정 breadcrumb를 넣어줘",
      "현재 위치 경로를 브레드크럼으로 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "breadcrumb",
      "props": {
        "depth": 3
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "navigation patterns"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "pagination",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "페이지네이션",
      "aliases": [
        "페이지 이동",
        "pagination"
      ]
    },
    "en": {
      "name": "Pagination",
      "aliases": [
        "Page navigation"
      ]
    },
    "one_liner": "긴 목록을 여러 페이지로 나누고 이동하게 하는 요소.",
    "description": "이전/다음, 페이지 번호, 현재 페이지 표시로 구성된다.",
    "visual_anatomy": [
      "previous button",
      "page numbers",
      "active page",
      "next button"
    ],
    "when_to_use": [
      "데이터가 많아 한 번에 모두 보여주기 어려울 때",
      "사용자가 위치를 유지하며 탐색해야 할 때"
    ],
    "anti_use": [
      "끊김 없는 탐색이 더 중요하면 infinite scroll을 검토한다",
      "적은 항목에는 불필요하다"
    ],
    "prompt_phrases": [
      "테이블 아래에 pagination을 넣어줘",
      "이전 다음 버튼과 페이지 번호를 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "pagination",
      "props": {
        "page": 2
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "pagination component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "stepper",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "스테퍼",
      "aliases": [
        "단계 표시",
        "progress steps",
        "단계 네비게이션"
      ]
    },
    "en": {
      "name": "Stepper",
      "aliases": [
        "Progress steps",
        "Wizard steps"
      ]
    },
    "one_liner": "여러 단계로 된 절차에서 현재 진행 단계를 보여주는 요소.",
    "description": "가입, 결제, 설정 마법사처럼 순서가 있는 과정을 단계로 표시한다.",
    "visual_anatomy": [
      "step indicators",
      "completed state",
      "active step",
      "connecting line"
    ],
    "when_to_use": [
      "사용자가 몇 단계 중 어디에 있는지 알아야 할 때",
      "순서대로 완료하는 흐름일 때"
    ],
    "anti_use": [
      "단일 화면 작업에는 과하다",
      "순서가 자유로운 탐색에는 tabs가 더 적합할 수 있다"
    ],
    "prompt_phrases": [
      "가입 절차를 보여주는 stepper를 넣어줘",
      "현재 2단계가 강조된 단계 표시를 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "stepper",
      "props": {
        "current": 2
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "progress and navigation pattern"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "navigation-rail",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "내비게이션 레일",
      "aliases": [
        "좌측 아이콘 메뉴",
        "nav rail"
      ]
    },
    "en": {
      "name": "Navigation rail",
      "aliases": [
        "Nav rail"
      ]
    },
    "one_liner": "화면 한쪽에 세로로 배치된 주요 목적지 이동 영역.",
    "description": "아이콘과 짧은 라벨로 주요 섹션을 전환하며 데스크톱/태블릿 레이아웃에서 자주 쓰인다.",
    "visual_anatomy": [
      "vertical rail",
      "destination icons",
      "active indicator",
      "optional labels"
    ],
    "when_to_use": [
      "앱의 주요 섹션이 3-7개일 때",
      "콘텐츠 영역을 넓게 유지하고 싶을 때"
    ],
    "anti_use": [
      "복잡한 계층 메뉴는 sidebar가 낫다",
      "모바일 하단 navigation과 경쟁시키지 않는다"
    ],
    "prompt_phrases": [
      "왼쪽에 아이콘 중심 navigation rail을 넣어줘",
      "현재 메뉴가 강조된 세로 내비게이션을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "navigation-rail",
      "props": {
        "active": 0
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "navigation rail component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "sidebar-nav",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "사이드바 내비게이션",
      "aliases": [
        "사이드 메뉴",
        "sidebar menu"
      ]
    },
    "en": {
      "name": "Sidebar navigation",
      "aliases": [
        "Side navigation",
        "Sidebar menu"
      ]
    },
    "one_liner": "화면 옆에 메뉴 목록을 세로로 배치한 내비게이션.",
    "description": "섹션, 하위 메뉴, active 상태를 함께 보여주며 관리 도구에 자주 쓰인다.",
    "visual_anatomy": [
      "side panel",
      "nav items",
      "active item",
      "optional nested groups"
    ],
    "when_to_use": [
      "대시보드나 관리 화면처럼 반복 탐색이 필요할 때",
      "메뉴 계층을 계속 보여줘야 할 때"
    ],
    "anti_use": [
      "단순 랜딩 페이지에는 과하다",
      "좁은 모바일에서는 drawer나 bottom nav로 바꾼다"
    ],
    "prompt_phrases": [
      "대시보드 왼쪽에 sidebar navigation을 넣어줘",
      "활성 메뉴가 표시된 사이드 메뉴를 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "sidebar-nav",
      "props": {
        "active": 1
      }
    },
    "sources": [
      {
        "source_id": "atlassian-design-components",
        "note": "side navigation pattern"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "chip",
    "status": "draft",
    "category": "selection",
    "ko": {
      "name": "칩",
      "aliases": [
        "태그 버튼",
        "pill",
        "chip"
      ]
    },
    "en": {
      "name": "Chip",
      "aliases": [
        "Pill",
        "Tag chip"
      ]
    },
    "one_liner": "작은 알약 모양으로 선택, 필터, 속성을 표시하는 요소.",
    "description": "라벨, 선택 상태, 삭제 아이콘을 조합해 필터나 태그를 표현한다.",
    "visual_anatomy": [
      "rounded pill container",
      "text label",
      "selected state",
      "optional remove icon"
    ],
    "when_to_use": [
      "선택된 필터를 보여줄 때",
      "항목의 짧은 속성이나 태그를 표시할 때"
    ],
    "anti_use": [
      "긴 설명 문장을 담지 않는다",
      "주요 CTA 버튼처럼 쓰지 않는다"
    ],
    "prompt_phrases": [
      "선택된 필터를 chip으로 보여줘",
      "삭제 가능한 태그 칩을 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "chip",
      "props": {
        "selected": true
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "chips component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "button",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "버튼",
      "aliases": [
        "button",
        "실행 버튼"
      ]
    },
    "en": {
      "name": "Button",
      "aliases": [
        "Action button"
      ]
    },
    "one_liner": "사용자가 눌러 명령이나 동작을 실행하는 요소.",
    "description": "라벨과 스타일로 행동의 의미와 중요도를 전달한다.",
    "visual_anatomy": [
      "button container",
      "label",
      "optional icon",
      "hover or pressed state"
    ],
    "when_to_use": [
      "사용자가 명확한 행동을 실행해야 할 때",
      "폼 제출이나 저장 같은 명령이 있을 때"
    ],
    "anti_use": [
      "페이지 이동만 의미하면 link를 검토한다",
      "상태 전환은 switch나 checkbox가 더 명확할 수 있다"
    ],
    "prompt_phrases": [
      "저장 버튼을 오른쪽 아래에 넣어줘",
      "폼 제출용 button을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "button",
      "props": {
        "emphasis": "default"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "buttons component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "primary-button",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "주요 버튼",
      "aliases": [
        "primary button",
        "메인 CTA"
      ]
    },
    "en": {
      "name": "Primary button",
      "aliases": [
        "Primary action",
        "CTA button"
      ]
    },
    "one_liner": "화면에서 가장 중요한 행동을 강조하는 버튼.",
    "description": "색상, 채움, 대비로 다른 버튼보다 강하게 보이게 만든다.",
    "visual_anatomy": [
      "filled container",
      "high contrast label",
      "optional leading icon"
    ],
    "when_to_use": [
      "사용자가 가장 먼저 해야 할 행동이 하나일 때",
      "저장 제출 시작 같은 핵심 CTA가 있을 때"
    ],
    "anti_use": [
      "한 화면에 너무 많이 두면 중요도가 흐려진다",
      "위험 행동은 destructive button으로 구분한다"
    ],
    "prompt_phrases": [
      "가장 중요한 행동은 primary button으로 강조해줘",
      "시작하기 CTA를 파란색 주요 버튼으로 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "primary-button",
      "props": {
        "label": "시작하기"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "button emphasis"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "secondary-button",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "보조 버튼",
      "aliases": [
        "secondary button",
        "outline button"
      ]
    },
    "en": {
      "name": "Secondary button",
      "aliases": [
        "Outline button",
        "Secondary action"
      ]
    },
    "one_liner": "주요 행동보다 덜 중요한 선택지를 제공하는 버튼.",
    "description": "테두리나 낮은 대비 스타일로 primary action보다 약하게 보인다.",
    "visual_anatomy": [
      "outlined or subtle container",
      "label",
      "lower visual weight"
    ],
    "when_to_use": [
      "취소",
      "나중에 하기",
      "보조 행동처럼 덜 중요한 명령이 있을 때"
    ],
    "anti_use": [
      "화면의 핵심 CTA를 secondary로 숨기지 않는다",
      "단순 링크는 link 스타일을 검토한다"
    ],
    "prompt_phrases": [
      "취소는 secondary button으로 넣어줘",
      "주요 버튼 옆에 보조 버튼을 배치해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "secondary-button",
      "props": {
        "label": "취소"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "button hierarchy"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "destructive-button",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "위험 버튼",
      "aliases": [
        "삭제 버튼",
        "destructive button",
        "danger button"
      ]
    },
    "en": {
      "name": "Destructive button",
      "aliases": [
        "Danger button",
        "Delete button"
      ]
    },
    "one_liner": "삭제나 되돌리기 어려운 위험한 행동을 나타내는 버튼.",
    "description": "보통 빨간색 계열과 경고 문맥으로 사용자가 위험을 인지하게 한다.",
    "visual_anatomy": [
      "danger color container or text",
      "warning label",
      "optional trash icon"
    ],
    "when_to_use": [
      "삭제",
      "초기화",
      "권한 해제처럼 손실 가능성이 있는 행동일 때"
    ],
    "anti_use": [
      "일반 실패 상태 강조에 남용하지 않는다",
      "위험 행동에는 확인 dialog를 함께 검토한다"
    ],
    "prompt_phrases": [
      "계정 삭제는 destructive button으로 표시해줘",
      "위험한 삭제 버튼은 빨간색으로 구분해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "destructive-button",
      "props": {
        "label": "삭제"
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "button variants"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "icon-button",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "아이콘 버튼",
      "aliases": [
        "icon button",
        "아이콘만 있는 버튼"
      ]
    },
    "en": {
      "name": "Icon button",
      "aliases": [
        "Icon-only button"
      ]
    },
    "one_liner": "텍스트 대신 아이콘으로 행동을 표현하는 버튼.",
    "description": "좋아요, 닫기, 검색, 설정처럼 익숙한 행동에 작은 공간으로 쓴다.",
    "visual_anatomy": [
      "square or circular hit area",
      "centered icon",
      "hover state",
      "accessible label"
    ],
    "when_to_use": [
      "아이콘 의미가 명확하고 공간이 좁을 때",
      "반복 카드 안의 빠른 행동이 필요할 때"
    ],
    "anti_use": [
      "낯선 아이콘은 텍스트 라벨이나 tooltip을 붙인다",
      "접근성 라벨 없이 쓰지 않는다"
    ],
    "prompt_phrases": [
      "카드 오른쪽에 하트 icon button을 넣어줘",
      "닫기 아이콘 버튼에는 tooltip을 붙여줘"
    ],
    "asset": {
      "kind": "icon-composition",
      "variant": "icon-button",
      "props": {
        "icon": "heart"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "icon buttons"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "floating-action-button",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "플로팅 버튼",
      "aliases": [
        "FAB",
        "floating action button",
        "떠 있는 버튼"
      ]
    },
    "en": {
      "name": "Floating action button",
      "aliases": [
        "FAB"
      ]
    },
    "one_liner": "화면 위에 떠 있는 핵심 행동 버튼.",
    "description": "보통 둥글거나 확장형이며 새 항목 만들기 같은 주요 행동을 항상 보이게 한다.",
    "visual_anatomy": [
      "floating circular button",
      "elevation shadow",
      "icon",
      "fixed position"
    ],
    "when_to_use": [
      "모바일이나 앱 화면에서 가장 중요한 생성 행동을 빠르게 제공할 때"
    ],
    "anti_use": [
      "여러 개를 남발하지 않는다",
      "일반 폼 제출 버튼 대신 쓰지 않는다"
    ],
    "prompt_phrases": [
      "오른쪽 아래에 플러스 FAB를 넣어줘",
      "새 글 작성 floating action button을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "floating-action-button",
      "props": {
        "icon": "plus"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "floating action button"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "link",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "링크",
      "aliases": [
        "텍스트 링크",
        "link"
      ]
    },
    "en": {
      "name": "Link",
      "aliases": [
        "Text link",
        "Hyperlink"
      ]
    },
    "one_liner": "다른 위치나 페이지로 이동하는 텍스트 요소.",
    "description": "밑줄, 색상, 화살표 등으로 클릭 가능한 이동을 나타낸다.",
    "visual_anatomy": [
      "text label",
      "link color",
      "underline or arrow",
      "hover state"
    ],
    "when_to_use": [
      "페이지 이동이나 외부 문서 열기처럼 navigation이 목적일 때"
    ],
    "anti_use": [
      "명령 실행에는 button을 쓴다",
      "중요한 CTA를 작은 링크로 숨기지 않는다"
    ],
    "prompt_phrases": [
      "자세히 보기 link를 카드 아래에 넣어줘",
      "외부 문서로 이동하는 텍스트 링크를 추가해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "link",
      "props": {
        "arrow": true
      }
    },
    "sources": [
      {
        "source_id": "apple-hig-components",
        "note": "links and controls distinction"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "toolbar",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "툴바",
      "aliases": [
        "도구막대",
        "toolbar"
      ]
    },
    "en": {
      "name": "Toolbar",
      "aliases": [
        "Action toolbar"
      ]
    },
    "one_liner": "관련 명령 버튼들을 한 줄이나 한 영역에 모은 도구 영역.",
    "description": "편집, 정렬, 필터, 보기 전환 같은 반복 행동을 한 곳에 배치한다.",
    "visual_anatomy": [
      "horizontal action group",
      "icon buttons",
      "separators",
      "optional dropdowns"
    ],
    "when_to_use": [
      "여러 명령을 빠르게 반복 실행해야 할 때",
      "편집기나 데이터 화면의 도구를 모을 때"
    ],
    "anti_use": [
      "명령이 한두 개뿐이면 과하다",
      "서로 무관한 행동을 한 툴바에 섞지 않는다"
    ],
    "prompt_phrases": [
      "표 위에 필터와 정렬 toolbar를 넣어줘",
      "에디터 상단에 아이콘 툴바를 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "toolbar",
      "props": {
        "items": 4
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "toolbar pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "split-button",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "스플릿 버튼",
      "aliases": [
        "분리 버튼",
        "split button"
      ]
    },
    "en": {
      "name": "Split button",
      "aliases": [
        "Button with menu"
      ]
    },
    "one_liner": "기본 행동과 추가 옵션 메뉴를 한 버튼 안에 나눈 요소.",
    "description": "왼쪽은 기본 실행, 오른쪽 화살표는 관련 옵션 목록을 여는 식으로 구성된다.",
    "visual_anatomy": [
      "primary action segment",
      "divider",
      "chevron segment",
      "optional menu"
    ],
    "when_to_use": [
      "가장 흔한 행동은 즉시 실행하고 변형 옵션도 제공해야 할 때"
    ],
    "anti_use": [
      "사용자가 기본 행동을 혼동할 수 있으면 일반 dropdown menu가 낫다",
      "모바일 좁은 영역에는 부담스럽다"
    ],
    "prompt_phrases": [
      "내보내기 버튼을 split button으로 만들어서 CSV와 PDF 옵션을 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "split-button",
      "props": {
        "open": false
      }
    },
    "sources": [
      {
        "source_id": "fluent2-react-components",
        "note": "split button component"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "menu-item",
    "status": "draft",
    "category": "action",
    "ko": {
      "name": "메뉴 항목",
      "aliases": [
        "menu item",
        "메뉴 아이템"
      ]
    },
    "en": {
      "name": "Menu item",
      "aliases": [
        "Menu option"
      ]
    },
    "one_liner": "메뉴 안에서 하나의 명령이나 선택지를 나타내는 행.",
    "description": "라벨, 아이콘, 단축키, 위험 상태 등을 한 줄에 표시한다.",
    "visual_anatomy": [
      "row container",
      "optional icon",
      "label",
      "shortcut or checkmark"
    ],
    "when_to_use": [
      "dropdown menu나 command menu 안의 개별 행동을 보여줄 때"
    ],
    "anti_use": [
      "독립적인 주요 행동은 메뉴 안에 숨기지 않는다",
      "긴 설명을 메뉴 항목에 넣지 않는다"
    ],
    "prompt_phrases": [
      "드롭다운 안에 삭제 menu item을 넣어줘",
      "메뉴 항목 오른쪽에 단축키를 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "menu-item",
      "props": {
        "icon": true
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "menu item behavior"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "card",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "카드",
      "aliases": [
        "card",
        "정보 카드"
      ]
    },
    "en": {
      "name": "Card",
      "aliases": [
        "Content card"
      ]
    },
    "one_liner": "관련 정보를 하나의 박스 안에 묶어 보여주는 컨테이너.",
    "description": "제목, 설명, 이미지, 행동 버튼을 한 덩어리로 묶어 스캔하기 쉽게 한다.",
    "visual_anatomy": [
      "container",
      "title",
      "body text",
      "optional media",
      "optional actions"
    ],
    "when_to_use": [
      "반복되는 항목을 목록이나 그리드로 보여줄 때",
      "하나의 주제를 독립적으로 묶을 때"
    ],
    "anti_use": [
      "페이지 섹션 전체를 카드처럼 중첩하지 않는다",
      "단순 텍스트 한 줄만 담기에는 과하다"
    ],
    "prompt_phrases": [
      "각 기능을 card로 묶어서 보여줘",
      "이미지와 설명이 있는 정보 카드를 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "card",
      "props": {
        "media": true
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "card component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "dialog",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "모달",
      "aliases": [
        "다이얼로그",
        "modal",
        "dialog"
      ]
    },
    "en": {
      "name": "Dialog",
      "aliases": [
        "Modal",
        "Modal dialog"
      ]
    },
    "one_liner": "현재 화면 위에 떠서 사용자의 집중 행동을 요구하는 창.",
    "description": "배경을 덮고 제목, 내용, 행동 버튼을 보여주며 닫기 전까지 주의를 모은다.",
    "visual_anatomy": [
      "backdrop",
      "dialog surface",
      "title",
      "content",
      "action buttons",
      "close button"
    ],
    "when_to_use": [
      "확인",
      "입력",
      "중요한 결정을 화면 흐름 위에서 처리할 때"
    ],
    "anti_use": [
      "단순 안내는 toast나 banner가 낫다",
      "긴 복잡한 작업은 별도 페이지나 drawer가 적합할 수 있다"
    ],
    "prompt_phrases": [
      "삭제 확인 modal을 띄워줘",
      "화면 중앙에 dialog를 열고 취소와 삭제 버튼을 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "dialog",
      "props": {
        "open": true
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "dialog modal pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "drawer",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "드로어",
      "aliases": [
        "시트",
        "사이드 패널",
        "drawer",
        "sheet"
      ]
    },
    "en": {
      "name": "Drawer",
      "aliases": [
        "Sheet",
        "Side panel"
      ]
    },
    "one_liner": "화면 한쪽에서 밀려 나오는 보조 패널.",
    "description": "세부 정보, 필터, 편집 폼을 현재 화면 맥락 안에서 보여준다.",
    "visual_anatomy": [
      "side or bottom panel",
      "backdrop optional",
      "handle or close button",
      "content area"
    ],
    "when_to_use": [
      "현재 목록을 유지한 채 상세나 설정을 보여줄 때",
      "필터 패널을 옆에서 열 때"
    ],
    "anti_use": [
      "사용자의 즉각 확인이 필요한 경고에는 dialog가 더 명확하다",
      "전체 작업 흐름은 page가 낫다"
    ],
    "prompt_phrases": [
      "오른쪽에서 열리는 drawer에 상세 정보를 보여줘",
      "모바일에서는 bottom sheet로 열리게 해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "drawer",
      "props": {
        "side": "right"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "navigation drawer and sheet-like surfaces"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "popover",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "팝오버",
      "aliases": [
        "작은 떠있는 패널",
        "popover"
      ]
    },
    "en": {
      "name": "Popover",
      "aliases": [
        "Floating panel"
      ]
    },
    "one_liner": "특정 트리거 근처에 뜨는 작은 보조 패널.",
    "description": "날짜 선택, 간단한 설정, 보조 정보를 현재 위치 근처에서 보여준다.",
    "visual_anatomy": [
      "trigger",
      "floating panel",
      "arrow optional",
      "compact content"
    ],
    "when_to_use": [
      "작은 입력이나 보조 정보를 주변 맥락에서 보여줄 때"
    ],
    "anti_use": [
      "중요한 결정이나 긴 내용은 dialog나 drawer가 낫다",
      "hover-only 정보는 tooltip을 검토한다"
    ],
    "prompt_phrases": [
      "버튼을 누르면 작은 popover가 열리게 해줘",
      "날짜 선택기를 팝오버로 띄워줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "popover",
      "props": {
        "open": true
      }
    },
    "sources": [
      {
        "source_id": "radix-ui-primitives",
        "note": "popover primitive"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "header",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "헤더",
      "aliases": [
        "상단바",
        "top bar",
        "header"
      ]
    },
    "en": {
      "name": "Header",
      "aliases": [
        "Top bar",
        "App header"
      ]
    },
    "one_liner": "화면 상단에서 브랜드, 제목, 주요 동작을 담는 영역.",
    "description": "로고, 페이지 제목, 검색, 내비게이션, 사용자 메뉴가 배치된다.",
    "visual_anatomy": [
      "top container",
      "brand or title",
      "navigation",
      "actions",
      "profile area"
    ],
    "when_to_use": [
      "페이지의 정체성과 주요 이동/행동을 항상 보여줘야 할 때"
    ],
    "anti_use": [
      "콘텐츠보다 과하게 커지면 작업 화면의 밀도가 낮아진다",
      "모바일에서는 간결해야 한다"
    ],
    "prompt_phrases": [
      "상단에 로고와 검색창이 있는 header를 넣어줘",
      "오른쪽에 사용자 메뉴가 있는 top bar를 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "header",
      "props": {
        "search": true
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "top app bar component"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "footer",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "푸터",
      "aliases": [
        "하단 영역",
        "footer"
      ]
    },
    "en": {
      "name": "Footer",
      "aliases": [
        "Page footer"
      ]
    },
    "one_liner": "화면 하단에서 보조 링크와 메타 정보를 담는 영역.",
    "description": "저작권, 정책 링크, 보조 navigation, 연락처 등을 정리한다.",
    "visual_anatomy": [
      "bottom container",
      "link groups",
      "metadata",
      "optional social icons"
    ],
    "when_to_use": [
      "웹사이트 하단에 반복되는 보조 정보를 제공할 때"
    ],
    "anti_use": [
      "앱의 핵심 명령을 footer에 숨기지 않는다",
      "모바일 고정 하단바와 혼동하지 않는다"
    ],
    "prompt_phrases": [
      "페이지 아래에 정책 링크가 있는 footer를 넣어줘",
      "하단에 저작권과 보조 링크를 정리해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "footer",
      "props": {
        "columns": 3
      }
    },
    "sources": [
      {
        "source_id": "apple-hig-components",
        "note": "layout and navigation conventions"
      }
    ],
    "confidence": "low"
  },
  {
    "id": "grid",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "그리드",
      "aliases": [
        "격자 배치",
        "grid layout"
      ]
    },
    "en": {
      "name": "Grid",
      "aliases": [
        "Grid layout"
      ]
    },
    "one_liner": "항목을 행과 열의 격자로 배치하는 레이아웃.",
    "description": "카드, 이미지, 상품, 용어 목록처럼 반복 항목을 균일하게 보여준다.",
    "visual_anatomy": [
      "columns",
      "rows",
      "gutters",
      "repeated items"
    ],
    "when_to_use": [
      "비슷한 항목을 한눈에 비교하거나 스캔하게 할 때"
    ],
    "anti_use": [
      "순서와 읽기 흐름이 중요하면 list가 낫다",
      "항목 크기가 제각각이면 masonry나 다른 구조를 검토한다"
    ],
    "prompt_phrases": [
      "카드를 3열 grid로 배치해줘",
      "용어 목록을 반응형 그리드로 보여줘"
    ],
    "asset": {
      "kind": "diagram",
      "variant": "grid",
      "props": {
        "columns": 3,
        "rows": 2
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "layout grid guidance"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "list",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "리스트",
      "aliases": [
        "목록",
        "list"
      ]
    },
    "en": {
      "name": "List",
      "aliases": [
        "List view"
      ]
    },
    "one_liner": "항목을 세로로 나열해 읽고 선택하게 하는 구조.",
    "description": "각 행은 텍스트, 아이콘, 보조 정보, 행동을 가질 수 있다.",
    "visual_anatomy": [
      "stacked rows",
      "primary text",
      "secondary text",
      "optional leading icon"
    ],
    "when_to_use": [
      "항목을 순서대로 읽거나 비교해야 할 때",
      "모바일에서 스캔 가능한 목록이 필요할 때"
    ],
    "anti_use": [
      "시각 비교가 중요하면 grid나 card layout이 낫다",
      "표 형식의 행열 데이터는 table을 쓴다"
    ],
    "prompt_phrases": [
      "알림을 list로 세로 나열해줘",
      "각 행에 아이콘과 설명이 있는 목록을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "list",
      "props": {
        "rows": 3
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "lists component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "accordion",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "아코디언",
      "aliases": [
        "접히는 목록",
        "accordion"
      ]
    },
    "en": {
      "name": "Accordion",
      "aliases": [
        "Disclosure list"
      ]
    },
    "one_liner": "제목을 누르면 내용을 펼치거나 접는 구조.",
    "description": "FAQ나 설정 그룹처럼 많은 내용을 압축해 보여준다.",
    "visual_anatomy": [
      "accordion item",
      "trigger row",
      "chevron",
      "expanded content panel"
    ],
    "when_to_use": [
      "여러 섹션 중 필요한 내용만 펼쳐 보게 할 때",
      "FAQ처럼 질문과 답변을 묶을 때"
    ],
    "anti_use": [
      "항상 비교해야 하는 정보는 접지 않는다",
      "핵심 정보를 숨기는 용도로 쓰지 않는다"
    ],
    "prompt_phrases": [
      "FAQ를 accordion으로 만들어줘",
      "각 항목을 접고 펼칠 수 있게 해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "accordion",
      "props": {
        "openIndex": 0
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "accordion pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "carousel",
    "status": "draft",
    "category": "structure",
    "ko": {
      "name": "캐러셀",
      "aliases": [
        "슬라이드 카드",
        "carousel"
      ]
    },
    "en": {
      "name": "Carousel",
      "aliases": [
        "Slider carousel"
      ]
    },
    "one_liner": "여러 콘텐츠를 좌우로 넘겨 보는 구조.",
    "description": "카드나 이미지를 한 번에 일부만 보여주고 이전/다음으로 이동한다.",
    "visual_anatomy": [
      "viewport",
      "slides",
      "previous and next controls",
      "indicators"
    ],
    "when_to_use": [
      "추천 카드나 이미지 묶음을 제한된 공간에서 보여줄 때"
    ],
    "anti_use": [
      "중요 정보를 숨기기 쉽다",
      "사용자가 반드시 봐야 하는 콘텐츠에는 부적합하다"
    ],
    "prompt_phrases": [
      "추천 카드를 carousel로 넘기게 해줘",
      "좌우 화살표가 있는 슬라이드 영역을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "carousel",
      "props": {
        "slides": 3
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "carousel component"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "tooltip",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "툴팁",
      "aliases": [
        "도움말 말풍선",
        "tooltip"
      ]
    },
    "en": {
      "name": "Tooltip",
      "aliases": [
        "Hint bubble"
      ]
    },
    "one_liner": "hover나 focus 때 짧은 설명을 보여주는 작은 도움말.",
    "description": "아이콘 버튼이나 낯선 용어의 의미를 짧게 보충한다.",
    "visual_anatomy": [
      "trigger element",
      "small floating bubble",
      "short text",
      "optional arrow"
    ],
    "when_to_use": [
      "아이콘 의미를 보충할 때",
      "짧은 보조 설명이 필요할 때"
    ],
    "anti_use": [
      "중요한 정보를 tooltip에만 숨기지 않는다",
      "긴 설명이나 상호작용 요소를 넣지 않는다"
    ],
    "prompt_phrases": [
      "아이콘 버튼에 tooltip을 붙여줘",
      "hover하면 짧은 도움말이 나오게 해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "tooltip",
      "props": {
        "open": true
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "tooltip pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "toast",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "토스트",
      "aliases": [
        "스낵바",
        "toast",
        "snackbar"
      ]
    },
    "en": {
      "name": "Toast",
      "aliases": [
        "Snackbar",
        "Notification toast"
      ]
    },
    "one_liner": "작업 결과를 잠깐 보여주고 사라지는 작은 알림.",
    "description": "저장 완료, 복사 완료, 오류처럼 즉각적인 피드백을 화면 가장자리에서 보여준다.",
    "visual_anatomy": [
      "floating notification",
      "message text",
      "icon optional",
      "close or action button"
    ],
    "when_to_use": [
      "사용자 행동 직후 결과를 짧게 알려줄 때",
      "화면 흐름을 막지 않아야 할 때"
    ],
    "anti_use": [
      "중요한 결정이나 긴 오류 설명은 dialog나 alert를 쓴다",
      "사용자가 반드시 읽어야 하는 정보를 자동으로 사라지게 하지 않는다"
    ],
    "prompt_phrases": [
      "저장되면 오른쪽 아래에 toast를 띄워줘",
      "복사 완료 스낵바를 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "toast",
      "props": {
        "tone": "success"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "snackbar component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "alert",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "알림 배너",
      "aliases": [
        "alert",
        "banner",
        "경고 박스"
      ]
    },
    "en": {
      "name": "Alert",
      "aliases": [
        "Banner",
        "Inline alert"
      ]
    },
    "one_liner": "중요한 상태나 경고를 지속적으로 보여주는 메시지 영역.",
    "description": "페이지 안에 배치되어 정보, 성공, 경고, 오류 상태를 설명한다.",
    "visual_anatomy": [
      "status icon",
      "message",
      "colored container",
      "optional action"
    ],
    "when_to_use": [
      "사용자가 알아야 하는 상태를 화면 안에 유지해야 할 때",
      "오류나 경고를 맥락 안에서 설명할 때"
    ],
    "anti_use": [
      "짧은 완료 피드백은 toast가 낫다",
      "확인을 요구하는 위험 행동은 dialog를 검토한다"
    ],
    "prompt_phrases": [
      "상단에 오류 alert banner를 보여줘",
      "결제 실패 안내를 inline alert로 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "alert",
      "props": {
        "tone": "warning"
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "alert component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "badge",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "배지",
      "aliases": [
        "badge",
        "숫자 표시",
        "상태 표시"
      ]
    },
    "en": {
      "name": "Badge",
      "aliases": [
        "Status badge",
        "Count badge"
      ]
    },
    "one_liner": "숫자나 짧은 상태를 작게 강조하는 표시.",
    "description": "알림 개수, 상태, 라벨을 작고 눈에 띄게 보여준다.",
    "visual_anatomy": [
      "small pill or dot",
      "count or label",
      "status color"
    ],
    "when_to_use": [
      "읽지 않은 개수나 상태를 빠르게 표시할 때",
      "카드나 메뉴 옆에 짧은 메타 정보를 붙일 때"
    ],
    "anti_use": [
      "긴 문장을 담지 않는다",
      "주요 행동 버튼처럼 쓰지 않는다"
    ],
    "prompt_phrases": [
      "알림 아이콘 위에 숫자 badge를 붙여줘",
      "상태를 초록색 배지로 표시해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "badge",
      "props": {
        "count": 3
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "badges component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "progress-bar",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "진행바",
      "aliases": [
        "프로그레스 바",
        "progress bar"
      ]
    },
    "en": {
      "name": "Progress bar",
      "aliases": [
        "Linear progress"
      ]
    },
    "one_liner": "작업 진행 정도를 막대 길이로 보여주는 요소.",
    "description": "업로드, 설치, 단계 진행처럼 전체 대비 현재 진행률을 시각화한다.",
    "visual_anatomy": [
      "track",
      "filled indicator",
      "optional percentage label"
    ],
    "when_to_use": [
      "진행률을 알 수 있고 사용자가 기다려야 할 때",
      "긴 작업의 상태를 안정적으로 보여줄 때"
    ],
    "anti_use": [
      "진행률을 알 수 없으면 spinner나 indeterminate progress를 쓴다",
      "짧은 즉시 동작에는 불필요하다"
    ],
    "prompt_phrases": [
      "업로드 진행률을 progress bar로 보여줘",
      "65퍼센트가 채워진 진행바를 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "progress-bar",
      "props": {
        "value": 65
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "progress indicators"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "spinner",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "로딩 스피너",
      "aliases": [
        "spinner",
        "loading indicator"
      ]
    },
    "en": {
      "name": "Spinner",
      "aliases": [
        "Loading spinner",
        "Circular progress"
      ]
    },
    "one_liner": "작업 중임을 회전 애니메이션으로 보여주는 로딩 표시.",
    "description": "정확한 진행률은 모르지만 처리 중임을 알려야 할 때 쓴다.",
    "visual_anatomy": [
      "circular ring",
      "rotating gap",
      "loading label optional"
    ],
    "when_to_use": [
      "짧은 비동기 처리 중 상태를 알려야 할 때",
      "진행률을 측정할 수 없을 때"
    ],
    "anti_use": [
      "긴 작업에는 설명과 progress bar를 함께 검토한다",
      "화면 전체를 불필요하게 막지 않는다"
    ],
    "prompt_phrases": [
      "데이터 불러오는 동안 loading spinner를 보여줘",
      "버튼 안에 작은 스피너를 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "spinner",
      "props": {
        "size": "sm"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "circular progress indicator"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "skeleton",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "스켈레톤",
      "aliases": [
        "skeleton loader",
        "로딩 자리표시자"
      ]
    },
    "en": {
      "name": "Skeleton",
      "aliases": [
        "Skeleton loader",
        "Placeholder"
      ]
    },
    "one_liner": "실제 콘텐츠가 들어올 자리의 형태를 미리 보여주는 로딩 UI.",
    "description": "카드, 텍스트, 이미지 영역의 회색 블록을 보여줘 로딩 중 레이아웃을 예측하게 한다.",
    "visual_anatomy": [
      "placeholder blocks",
      "text lines",
      "media rectangle",
      "subtle shimmer optional"
    ],
    "when_to_use": [
      "콘텐츠 구조를 알고 있고 로딩 시간이 체감될 때",
      "레이아웃 점프를 줄이고 싶을 때"
    ],
    "anti_use": [
      "매우 짧은 로딩에는 과하다",
      "실제 구조와 다른 skeleton은 혼란을 준다"
    ],
    "prompt_phrases": [
      "카드 목록 로딩 중에는 skeleton loader를 보여줘",
      "이미지와 텍스트 자리표시자를 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "skeleton",
      "props": {
        "rows": 3
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "skeleton component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "empty-state",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "빈 상태",
      "aliases": [
        "empty state",
        "데이터 없음 화면"
      ]
    },
    "en": {
      "name": "Empty state",
      "aliases": [
        "No data state"
      ]
    },
    "one_liner": "보여줄 데이터가 없을 때 이유와 다음 행동을 안내하는 화면.",
    "description": "아이콘, 짧은 문구, 보조 설명, 생성 버튼으로 빈 화면을 의미 있게 만든다.",
    "visual_anatomy": [
      "empty icon or illustration",
      "title",
      "explanation",
      "optional action button"
    ],
    "when_to_use": [
      "검색 결과가 없거나 아직 데이터가 없을 때",
      "사용자가 다음 행동을 알아야 할 때"
    ],
    "anti_use": [
      "오류 상태와 섞지 않는다",
      "빈 화면을 아무 설명 없이 방치하지 않는다"
    ],
    "prompt_phrases": [
      "데이터가 없을 때 empty state를 보여줘",
      "빈 목록에는 새 항목 만들기 버튼을 넣어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "empty-state",
      "props": {
        "action": true
      }
    },
    "sources": [
      {
        "source_id": "carbon-design-components",
        "note": "empty states guidance"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "validation-message",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "검증 메시지",
      "aliases": [
        "입력 오류 문구",
        "validation error",
        "helper text"
      ]
    },
    "en": {
      "name": "Validation message",
      "aliases": [
        "Error message",
        "Helper text"
      ]
    },
    "one_liner": "입력값의 오류나 도움말을 필드 근처에서 알려주는 문구.",
    "description": "어떤 값이 왜 잘못됐고 어떻게 고쳐야 하는지 입력 요소 바로 아래에 표시한다.",
    "visual_anatomy": [
      "field",
      "error color",
      "message text",
      "optional error icon"
    ],
    "when_to_use": [
      "폼 입력값이 잘못됐거나 형식 안내가 필요할 때"
    ],
    "anti_use": [
      "오류를 필드와 떨어진 곳에만 표시하지 않는다",
      "모호한 문구만 쓰지 않는다"
    ],
    "prompt_phrases": [
      "이메일 형식이 틀리면 validation message를 입력창 아래에 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "validation-message",
      "props": {
        "tone": "error"
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "text field supporting text and error"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "status-indicator",
    "status": "draft",
    "category": "feedback",
    "ko": {
      "name": "상태 표시",
      "aliases": [
        "status indicator",
        "상태 점",
        "presence"
      ]
    },
    "en": {
      "name": "Status indicator",
      "aliases": [
        "Presence indicator",
        "Status dot"
      ]
    },
    "one_liner": "온라인, 성공, 오류 같은 상태를 작은 색상 표시로 보여주는 요소.",
    "description": "점, 라벨, 색상으로 항목이나 사용자의 현재 상태를 빠르게 전달한다.",
    "visual_anatomy": [
      "colored dot",
      "short label",
      "optional outline or pulse"
    ],
    "when_to_use": [
      "서버 상태",
      "사용자 접속 상태",
      "처리 상태를 빠르게 구분할 때"
    ],
    "anti_use": [
      "색상만으로 의미를 전달하지 않는다",
      "복잡한 설명은 alert나 detail text를 함께 쓴다"
    ],
    "prompt_phrases": [
      "온라인 상태를 초록색 status indicator로 표시해줘",
      "서버 상태 옆에 상태 점을 붙여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "status-indicator",
      "props": {
        "tone": "online"
      }
    },
    "sources": [
      {
        "source_id": "fluent2-react-components",
        "note": "presence and status components"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "table",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "테이블",
      "aliases": [
        "표",
        "data table"
      ]
    },
    "en": {
      "name": "Table",
      "aliases": [
        "Data table"
      ]
    },
    "one_liner": "행과 열로 구조화된 데이터를 보여주는 요소.",
    "description": "같은 속성을 가진 여러 항목을 비교, 정렬, 스캔하게 한다.",
    "visual_anatomy": [
      "header row",
      "columns",
      "data rows",
      "cell borders or dividers"
    ],
    "when_to_use": [
      "여러 항목의 속성을 비교해야 할 때",
      "정렬이나 행 선택이 필요한 데이터 화면에서"
    ],
    "anti_use": [
      "모바일에서 열이 너무 많으면 카드나 list로 바꾼다",
      "단순 텍스트 목록에는 list가 낫다"
    ],
    "prompt_phrases": [
      "사용자 목록을 data table로 보여줘",
      "행과 열이 있는 테이블을 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "table",
      "props": {
        "rows": 3,
        "columns": 3
      }
    },
    "sources": [
      {
        "source_id": "carbon-design-components",
        "note": "data table component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "avatar",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "아바타",
      "aliases": [
        "프로필 이미지",
        "avatar"
      ]
    },
    "en": {
      "name": "Avatar",
      "aliases": [
        "User avatar",
        "Profile image"
      ]
    },
    "one_liner": "사용자나 조직을 나타내는 작은 이미지 또는 이니셜.",
    "description": "프로필 사진, 이니셜, fallback 색상으로 사람이나 계정을 식별한다.",
    "visual_anatomy": [
      "circular or rounded image",
      "fallback initials",
      "optional status badge"
    ],
    "when_to_use": [
      "사용자 목록",
      "댓글",
      "프로필 메뉴에서 사람을 빠르게 구분할 때"
    ],
    "anti_use": [
      "장식 이미지처럼 쓰지 않는다",
      "의미 없는 랜덤 이미지는 혼란을 줄 수 있다"
    ],
    "prompt_phrases": [
      "댓글 옆에 avatar를 넣어줘",
      "프로필 이미지가 없으면 이니셜을 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "avatar",
      "props": {
        "status": "online"
      }
    },
    "sources": [
      {
        "source_id": "shadcn-ui-docs",
        "note": "avatar component"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "metric-card",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "지표 카드",
      "aliases": [
        "통계 카드",
        "KPI card",
        "metric card"
      ]
    },
    "en": {
      "name": "Metric card",
      "aliases": [
        "Stat card",
        "KPI card"
      ]
    },
    "one_liner": "핵심 숫자와 변화량을 카드 형태로 보여주는 데이터 요소.",
    "description": "매출, 방문자, 전환율 같은 지표를 제목, 숫자, 증감 표시로 요약한다.",
    "visual_anatomy": [
      "label",
      "large value",
      "trend indicator",
      "supporting text"
    ],
    "when_to_use": [
      "대시보드에서 중요한 지표를 빠르게 훑게 할 때"
    ],
    "anti_use": [
      "원인 분석이나 상세 데이터는 chart나 table을 함께 제공한다",
      "너무 많은 지표 카드는 집중을 흐린다"
    ],
    "prompt_phrases": [
      "대시보드 상단에 metric card 4개를 배치해줘",
      "방문자 수와 증감률을 지표 카드로 보여줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "metric-card",
      "props": {
        "trend": "up"
      }
    },
    "sources": [
      {
        "source_id": "atlassian-design-components",
        "note": "dashboard display patterns"
      }
    ],
    "confidence": "low"
  },
  {
    "id": "chart",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "차트",
      "aliases": [
        "그래프",
        "chart"
      ]
    },
    "en": {
      "name": "Chart",
      "aliases": [
        "Graph",
        "Data visualization"
      ]
    },
    "one_liner": "숫자 데이터를 시각적 형태로 보여주는 요소.",
    "description": "막대, 선, 영역, 원형 등 데이터 관계에 맞는 형태로 추세나 비교를 표현한다.",
    "visual_anatomy": [
      "plot area",
      "axes or labels",
      "data marks",
      "legend optional"
    ],
    "when_to_use": [
      "추세",
      "비교",
      "분포를 숫자보다 빠르게 이해하게 할 때"
    ],
    "anti_use": [
      "값이 한두 개뿐이면 metric card나 plain text가 낫다",
      "장식용 차트는 피한다"
    ],
    "prompt_phrases": [
      "월별 매출을 line chart로 보여줘",
      "카테고리별 비중을 bar chart로 비교해줘"
    ],
    "asset": {
      "kind": "diagram",
      "variant": "chart",
      "props": {
        "type": "bar"
      }
    },
    "sources": [
      {
        "source_id": "carbon-design-components",
        "note": "data visualization guidance"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "timeline",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "타임라인",
      "aliases": [
        "이력 목록",
        "timeline"
      ]
    },
    "en": {
      "name": "Timeline",
      "aliases": [
        "Activity timeline"
      ]
    },
    "one_liner": "시간 순서대로 사건이나 활동을 보여주는 구조.",
    "description": "점, 선, 시간 라벨, 이벤트 카드로 변경 이력이나 진행 과정을 표현한다.",
    "visual_anatomy": [
      "vertical line",
      "event dots",
      "timestamps",
      "event content"
    ],
    "when_to_use": [
      "작업 이력",
      "배송 상태",
      "활동 로그처럼 순서가 중요한 데이터를 보여줄 때"
    ],
    "anti_use": [
      "순서가 중요하지 않은 항목은 list나 table이 낫다",
      "너무 많은 이벤트는 필터가 필요하다"
    ],
    "prompt_phrases": [
      "주문 상태를 timeline으로 보여줘",
      "활동 로그를 시간순 타임라인으로 정리해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "timeline",
      "props": {
        "events": 3
      }
    },
    "sources": [
      {
        "source_id": "atlassian-design-components",
        "note": "activity and status display patterns"
      }
    ],
    "confidence": "low"
  },
  {
    "id": "kanban",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "칸반",
      "aliases": [
        "kanban board",
        "보드"
      ]
    },
    "en": {
      "name": "Kanban",
      "aliases": [
        "Kanban board",
        "Board"
      ]
    },
    "one_liner": "항목을 상태별 열로 나눠 보여주는 보드 구조.",
    "description": "할 일, 진행 중, 완료처럼 상태 column과 draggable card로 작업 흐름을 표현한다.",
    "visual_anatomy": [
      "columns",
      "column headers",
      "cards",
      "drag handles optional"
    ],
    "when_to_use": [
      "작업이나 후보를 상태별로 이동시키며 관리할 때"
    ],
    "anti_use": [
      "정렬과 숫자 비교가 핵심이면 table이 낫다",
      "항목 수가 너무 많으면 필터와 검색이 필요하다"
    ],
    "prompt_phrases": [
      "작업을 할 일 진행 중 완료 kanban board로 보여줘",
      "카드를 상태별 열에 배치해줘"
    ],
    "asset": {
      "kind": "diagram",
      "variant": "kanban",
      "props": {
        "columns": 3
      }
    },
    "sources": [
      {
        "source_id": "atlassian-design-components",
        "note": "board-like work management patterns"
      }
    ],
    "confidence": "low"
  },
  {
    "id": "calendar-view",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "캘린더 뷰",
      "aliases": [
        "달력 화면",
        "calendar view"
      ]
    },
    "en": {
      "name": "Calendar view",
      "aliases": [
        "Calendar"
      ]
    },
    "one_liner": "날짜 격자 위에 일정이나 이벤트를 보여주는 화면.",
    "description": "월, 주, 일 단위로 날짜와 이벤트를 배치해 시간 기반 정보를 탐색하게 한다.",
    "visual_anatomy": [
      "date grid",
      "weekday header",
      "event chips",
      "current day highlight"
    ],
    "when_to_use": [
      "예약",
      "일정",
      "마감처럼 날짜 위치가 중요한 데이터를 보여줄 때"
    ],
    "anti_use": [
      "단순 날짜 선택은 date picker가 충분하다",
      "이벤트가 적으면 list가 더 읽기 쉽다"
    ],
    "prompt_phrases": [
      "마감 일정을 calendar view로 보여줘",
      "월간 달력에 이벤트 chip을 배치해줘"
    ],
    "asset": {
      "kind": "diagram",
      "variant": "calendar-view",
      "props": {
        "weeks": 2
      }
    },
    "sources": [
      {
        "source_id": "material-m3-components",
        "note": "date and calendar patterns"
      }
    ],
    "confidence": "medium"
  },
  {
    "id": "tree-view",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "트리 뷰",
      "aliases": [
        "계층 목록",
        "tree view"
      ]
    },
    "en": {
      "name": "Tree view",
      "aliases": [
        "Tree",
        "Hierarchical list"
      ]
    },
    "one_liner": "폴더처럼 계층 구조를 펼치고 접어 보는 목록.",
    "description": "부모와 자식 항목을 indentation, chevron, expanded state로 표현한다.",
    "visual_anatomy": [
      "nested rows",
      "disclosure chevrons",
      "indentation",
      "selected row"
    ],
    "when_to_use": [
      "폴더",
      "카테고리",
      "문서 구조처럼 계층이 중요한 데이터를 탐색할 때"
    ],
    "anti_use": [
      "계층이 얕으면 list나 accordion이 더 단순하다",
      "너무 깊은 구조는 검색이 필요하다"
    ],
    "prompt_phrases": [
      "파일 목록을 tree view로 보여줘",
      "카테고리를 펼치고 접는 계층 목록으로 만들어줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "tree-view",
      "props": {
        "expanded": true
      }
    },
    "sources": [
      {
        "source_id": "wai-aria-apg-patterns",
        "note": "treeview pattern"
      }
    ],
    "confidence": "high"
  },
  {
    "id": "description-list",
    "status": "draft",
    "category": "data-display",
    "ko": {
      "name": "설명 목록",
      "aliases": [
        "key value list",
        "속성 목록"
      ]
    },
    "en": {
      "name": "Description list",
      "aliases": [
        "Key-value list",
        "Detail list"
      ]
    },
    "one_liner": "이름과 값을 짝지어 상세 정보를 보여주는 목록.",
    "description": "프로필, 주문 상세, 설정 요약처럼 속성명과 값을 나란히 표시한다.",
    "visual_anatomy": [
      "term label",
      "value text",
      "repeated rows",
      "optional separators"
    ],
    "when_to_use": [
      "한 객체의 여러 속성을 읽기 쉽게 보여줄 때"
    ],
    "anti_use": [
      "여러 객체를 비교해야 하면 table이 낫다",
      "긴 본문에는 일반 text layout이 낫다"
    ],
    "prompt_phrases": [
      "주문 상세를 key-value list로 보여줘",
      "사용자 정보를 설명 목록으로 정리해줘"
    ],
    "asset": {
      "kind": "mini-mock",
      "variant": "description-list",
      "props": {
        "rows": 3
      }
    },
    "sources": [
      {
        "source_id": "carbon-design-components",
        "note": "structured data display patterns"
      }
    ],
    "confidence": "low"
  }
] satisfies VocabularyTerm[]

export const categories = [
  "input",
  "selection",
  "action",
  "structure",
  "feedback",
  "data-display"
] satisfies TermCategory[]
